continents:
  - name: Europe
    cities:
      - name: Berlin
        latitude: 52.52
        longitude: 13.41
      - name: Rome
        latitude: 41.90
        longitude: 12.50
      - name: Madrid
        latitude: 40.42
        longitude: -3.70

  - name: North America
    cities:
      - name: New York
        latitude: 40.71
        longitude: -74.01
      - name: Los Angeles
        latitude: 34.05
        longitude: -118.24
      - name: Toronto
        latitude: 43.65
        longitude: -79.38

  - name: Asia
    cities:
      - name: Tokyo
        latitude: 35.68
        longitude: 139.75
      - name: Singapore
        latitude: 1.35
        longitude: 103.82
      - name: Mumbai
        latitude: 19.07
        longitude: 72.88